name: Retrain Stock Model

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:  # allows manual run from GitHub

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install joblib

      - name: Run training script
        run: python train_model.py

      - name: Upload updated model
        uses: actions/upload-artifact@v3
        with:
          name: model-artifact
          path: model.pkl
